twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        username: "dddddd"
    form_themes:
        ['bootstrap_5_layout.html.twig', 'form/theme.html.twig']


when@test:
    twig:
        strict_variables: true
